import { supabase,chapters,accountEmail,youtubeEmbed,esc } from "./supabase.js?v=2";
const loginView=document.querySelector("#loginView"),memberView=document.querySelector("#memberView"),lessonsEl=document.querySelector("#lessons"),chapterEl=document.querySelector("#chapters"),toolPanel=document.querySelector("#toolPanel"),bonusPanel=document.querySelector("#bonusPanel"),lessonTab=document.querySelector("#lessonTab"),toolTab=document.querySelector("#toolTab"),bonusTab=document.querySelector("#bonusTab");let lessons=[],selected=1,activeTab="lessons";
const tools={1:{title:"AI活用ロードマップ",url:"./tool.html?chapter=1"},2:{title:"自分専用プロンプト集",url:"./tool.html?chapter=2"},3:{title:"仕事テンプレ・AIワークフロー",url:"./tool.html?chapter=3"},4:{title:"AI秘書・AI社員設計",url:"./tool.html?chapter=4"},5:{title:"Codex実践マニュアル",url:"./tool.html?chapter=5"},7:{title:"Instagram投稿10本作成",url:"./tool.html?chapter=7"},8:{title:"AIショート動画制作",url:"./tool.html?chapter=8"},9:{title:"AI商品完成スタジオ",url:"./tool.html?chapter=9"},10:{title:"専用アプリ設計ツール",url:"./tool.html?chapter=10"},12:{title:"AI COMPANY OS",url:"./tool.html?chapter=12"}};
const fallbackLessons=[
{chapter_id:1,sort_order:1,title:"第1章 時代に乗り遅れないAIの使い方",body:"AIの全体像を理解し、自分専用の活用ロードマップを完成させます。",youtube_url:"https://youtu.be/N5YyF5hrs1Y"},
{chapter_id:1,sort_order:2,title:"第1章 コンテンツツール",body:"学んだ内容を成果物に変える専用ツールの使い方です。",youtube_url:"https://youtu.be/TIcDlqahvtA"},
{chapter_id:2,sort_order:1,title:"第2章 AIへの指示の出し方・プロンプト完全攻略",body:"自分専用のプロンプト集と、繰り返し使える指示の型を完成させます。",youtube_url:"https://youtu.be/c0QLOF9c6Ho"},
{chapter_id:2,sort_order:2,title:"第2章 コンテンツツール",body:"プロンプトを実際に使える形へ整理する方法を解説します。",youtube_url:"https://youtu.be/NJF61D4FSNY"},
{chapter_id:3,sort_order:1,title:"第3章 ChatGPT仕事術｜AIを「使う」から「働いてもらう」へ",body:"仕事テンプレと毎日使うAIワークフローを構築します。",youtube_url:"https://youtu.be/5iOg8e47wmI"},
{chapter_id:3,sort_order:2,title:"第3章 コンテンツツール",body:"仕事で繰り返し使える形へ落とし込む実践編です。",youtube_url:"https://youtu.be/ZUeTJjmsNPE"},
{chapter_id:4,sort_order:1,title:"第4章 GPTs・AI秘書構築｜あなた専属のAI社員を作ろう",body:"自分の業務を理解し、実務を補助するAI秘書を完成させます。",youtube_url:"https://youtu.be/COka1mcLoRI"},
{chapter_id:4,sort_order:2,title:"第4章 コンテンツツール",body:"AI秘書を形にするための専用ツールを使います。",youtube_url:"https://youtu.be/TRdCGfThMCY"},
{chapter_id:5,sort_order:1,title:"第5章 Codex完全攻略",body:"Codexを使った制作と改善の基礎を身につけます。",youtube_url:"https://youtu.be/NQe-DAMeTg8"},
{chapter_id:6,sort_order:1,title:"第6章 Codex仕事自動化｜毎日繰り返す仕事はAIに任せよう",body:"繰り返し業務を自動化する考え方と実践手順を学びます。",youtube_url:"https://youtu.be/wM5u7RjUF0E"},
{chapter_id:7,sort_order:1,title:"第7章 AI×画像・SNS完全攻略",body:"画像制作とSNS発信の再現できる型を完成させます。",youtube_url:"https://youtu.be/lp6Au4xLT0I"},
{chapter_id:7,sort_order:2,title:"第7章 コンテンツツール",body:"投稿企画と制作を効率化する専用ツールの使い方です。",youtube_url:"https://youtu.be/jT437wg0LSw"},
{chapter_id:8,sort_order:1,title:"第8章 AI動画・ショート動画制作",body:"企画から公開までの動画制作フローを完成させます。",youtube_url:"https://youtu.be/SZgxwG6xLJE"},
{chapter_id:9,sort_order:1,title:"第9章 AIコンテンツ販売｜売れる商品を0から作ろう",body:"知識を商品に変え、販売するまでの導線を作ります。",youtube_url:"https://youtu.be/mz_zH6lhuZs"},
{chapter_id:10,sort_order:1,title:"第10章 AIアプリ開発｜アイデアを形にする",body:"自分や顧客の課題を解決するAIアプリを公開します。",youtube_url:"https://youtu.be/IvA7IX-FfjM"},
{chapter_id:11,sort_order:1,title:"第11章 AI自動化・API連携",body:"複数ツールをつなぎ、作業が流れる自動化を構築します。",youtube_url:"https://youtu.be/kDtrsjN_FYw"},
{chapter_id:12,sort_order:1,title:"第12章 AI会社設計・収益化",body:"AIを活用した事業と収益モデルを設計します。",youtube_url:"https://youtu.be/S4HUBYBgq5M"},
{chapter_id:13,sort_order:1,title:"第13章 実践ワーク｜5日間でAI事業を完成させよう",body:"これまでの学びを統合し、公開できる最終成果物を完成させます。",youtube_url:"https://youtu.be/d4WaGR2MQoE"}
];
document.querySelector("#loginForm").addEventListener("submit",async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const {error}=await supabase.auth.signInWithPassword({email:accountEmail(f.get("username")),password:f.get("password")});if(error)document.querySelector("#loginError").textContent="ユーザー名またはパスワードが正しくありません。";else showMembers();});
document.querySelector("#logout").onclick=async()=>{await supabase.auth.signOut();location.reload();};
async function showMembers(){const {data:{session}}=await supabase.auth.getSession();if(!session)return;loginView.hidden=true;memberView.hidden=false;chapterEl.innerHTML=chapters.map((c,i)=>`<button data-id="${i+1}" class="${i===0?'active':''}"><b>${String(i+1).padStart(2,'0')}</b>${esc(c)}</button>`).join("");chapterEl.querySelectorAll("button").forEach(b=>b.onclick=()=>{selected=Number(b.dataset.id);chapterEl.querySelectorAll("button").forEach(x=>x.classList.toggle("active",x===b));render();});lessonTab.onclick=()=>{activeTab="lessons";render()};toolTab.onclick=()=>{activeTab="tools";render()};bonusTab.onclick=()=>{activeTab="bonus";render()};const {data,error}=await supabase.from("lessons").select("*").order("sort_order").order("created_at");lessons=!error&&data?.length?data:fallbackLessons;render();}
function render(){const showTools=activeTab==="tools",showBonus=activeTab==="bonus";lessonTab.classList.toggle("active",!showTools&&!showBonus);toolTab.classList.toggle("active",showTools);bonusTab.classList.toggle("active",showBonus);lessonsEl.hidden=showTools||showBonus;toolPanel.hidden=!showTools;bonusPanel.hidden=!showBonus;if(showBonus){bonusPanel.innerHTML=`<article class="bonus-card"><div><span>AI LIFE MEMBERS BLOG</span><h2>AI LIFE実践ブログ</h2><p>ChatGPT・Codexの新しい使い方を、すぐ試せる文章・図解・コピペ用プロンプトで不定期更新しています。</p><div class="bonus-tags"><b>NEW</b> 新しい実践記事を7本公開しました</div><a href="./bonus/">実践ブログを読む →</a></div></article>`;return}if(showTools){const tool=tools[selected];toolPanel.innerHTML=tool?`<article class="tool-card"><span>✦ CHAPTER ${String(selected).padStart(2,"0")} TOOL</span><h2>${esc(tool.title)}</h2><p>この章の成果物を作成する専用ツールです。</p><a href="${esc(tool.url)}" target="_blank" rel="noopener">成果物ツールを開く ↗</a></article>`:`<div class="empty"><h2>この章の成果物ツールは準備中です</h2><p>公開までしばらくお待ちください。</p></div>`;return}const list=lessons.filter(x=>x.chapter_id===selected);lessonsEl.innerHTML=list.length?list.map(x=>{const embed=youtubeEmbed(x.youtube_url);const thumb=x.thumbnail_path?supabase.storage.from("thumbnails").getPublicUrl(x.thumbnail_path).data.publicUrl:"";return `<article class="lesson-card"><div class="video"><iframe src="${esc(embed)}" title="${esc(x.title)}" loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>${thumb?`<img src="${esc(thumb)}" alt="" class="poster">`:""}<button class="play" aria-label="動画を再生">▶</button></div><div class="lesson-body"><span class="badge">VIDEO</span><h2>${esc(x.title)}</h2><p>${esc(x.body||"")}</p></div></article>`}).join(""):`<div class="empty"><h2>この章の教材は準備中です</h2><p>公開までしばらくお待ちください。</p></div>`;lessonsEl.querySelectorAll(".video").forEach(v=>v.querySelector(".play")?.addEventListener("click",()=>{v.querySelector(".poster")?.remove();v.querySelector(".play")?.remove();}));}
showMembers();
